baseURL = "https://morethanmen.org"
languageCode = "en-us"
title = "More than Men"
theme = "ananke"
#languageCode = "en-us"
#theme = "gohugo-theme-ananke"
#themesDir = "../.."
resourceDir = "../resources"
#googleAnalytics = "UA-5215367-2"

[taxonomies]
   authors = "author"
   
#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#
#  [[menu.main]]
#    identifier = "blog"
#    name = "Blog"
#    url = "/posts/"
#
#  [[menu.main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact-me/"

[languages]
  [languages.en]
    title = "More than Men"
    weight = 1
    contentDir = "content/"

[params]
#  favicon = "favicon.ico"
#  site_logo = "/CTlogo.png"
  description = "Welcome to More than Men"
#  facebook = ""
#  twitter = "https://twitter.com/chaos46692"
#  instagram = "https://www.instagram.com/chaos46692/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
#  tiktok = "https://www.tiktok.com/@chaos46692"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  featured_image = "/images/bumpy1200.webp"
  recent_posts_number = 6
  omit_header_text = true
  custom_css = ["css/custom.css"]
  env="production"
  recent_copy="Recent Posts"


